### ISSUE TITLE
Documented commands to control Independent/Series/Parallel modes are available

### ISSUE THREAD

**Issue by benniju** [Kurokesu/siglent_psu_api#3]
There are actually documented commands for controlling the Output modes:

OUTP:TRACK {0|1|2}

| Command format | OUTPut:TRACK {0\|1\|2} |
| ------------------ | ------------------------ |
| Description | Select operation mode. |
| Parameters | {0\|1\|2} mean independent, series and parallel respectively. |
| Example | OUTPut: TRACK 0 |

Source: [the Manual](https://int.siglent.com/upload_file/user/SPD3000X/SPD3303X_QuickStart_QS0503X-E01B.pdf)

I also found these (OUTP:TRACK 2) when looking at captured wireshark traffic from the EASYcontrol Software.

**Comment by benniju** [comment]
Ok I just looked at your Code and saw that you have actually implemented this, but wrote that it does not work. 
For me it does, at least using the EASYcontrol, I will try it later by modifying your code.

One clue: You probably know this alredy, but some commands require the \n and others don't. I think that you have to send it in the same packet and not after sending the command (as the commented code would suggest):

![grafik](https://user-images.githubusercontent.com/33903843/111885995-658c6c00-89cb-11eb-9ebc-9aa0ea97b66e.png)

**Comment by benniju** [comment]
I have sucessfully fixed this, just by adding the \n directly to the command in https://github.com/Kurokesu/siglent_psu_api/pull/4.

PS: This is my first PR, so please forgive me for all the mistakes I probably made.

**Comment by Lukse** [comment]
Thank you! Looks like track mode switch was fixed with previous bug fix (new line issue). So just removed exception note and committing changes to master repository.
