### ISSUE TITLE
CC and CV modes reversed

### ISSUE THREAD

**Issue by w4jbm** [Kurokesu/siglent_psu_api#5]
In the logic to determine whether the supply is in Constant Voltage (CV) or Constant Current (CC) mode, the check of the bit appears to be reversed. For Channel 1, if Bit 0 is not set, the supply is in CV mode. If Bit 0 is set, the supply is in CC mode. The code seems to use an IF statement with a logical AND, but if the check is TRUE, it should return CC mode instead of CV mode. Usually the test will be FALSE (Bit 0 is not set) which would fall through to the ELSE statement and indicate the supply is in CV mode.

**Comment by Lukse** [comment]
Thank you! Fixed.
